app/school/models.py
from app.models import db, generate_table_name
from peewee import *

class School(Model):
    school_id = PrimaryKeyField(db_column="ID")
    school_name = CharField(max_length=255, unique=True, db_column="SCHOOL_NAME")

    class Meta:
        database = db
        db_table = "TBL_SCHOOL"

app/school/forms.py
from flask_wtf import (
    Form,
)

from wtforms import (
    StringField,
    PasswordField,
    SelectField,
    BooleanField,
)

from wtforms.validators import (
    DataRequired,
    ValidationError,
    Length,
    EqualTo,
)

from .models import School


def school_exists(form, field):
    if School.select().where(School.school_name == field.data).exists():
        raise ValidationError("School already in use.")


class SignUpForm(Form):
    school_name = StringField("School Name", validators=[DataRequired(), school_exists])
    forename = StringField("Forename", validators=[DataRequired()])
    surname = StringField("Surname", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=5), EqualTo("password2", message="Passwords must match.")])
    password2 = PasswordField("Confirm Password", validators=[DataRequired()])


class NewUserForm(Form):
    forename = StringField("Forename", validators=[DataRequired()])
    surname = StringField("Surname", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=5), EqualTo("password2", message="Passwords must match.")])
    password2 = PasswordField("Confirm Password", validators=[DataRequired()])
    is_admin = BooleanField("Is Admin")
    is_teacher = BooleanField("Is Teacher")
    is_student = BooleanField("Is Student")


class ModifyUserForm(Form):
    forename = StringField("Forename", validators=[DataRequired()])
    surname = StringField("Surname", validators=[DataRequired()])
    is_admin = BooleanField("Is Admin")
    is_teacher = BooleanField("Is Teacher")
    is_student = BooleanField("Is Student")

app/school/views.py
from flask import Blueprint, render_template, redirect, url_for, g, flash, request
from flask.ext.login import login_required
from .models import School
from .forms import SignUpForm, NewUserForm, ModifyUserForm
from .functions import create_school, get_users_in_school, get_role_names
from app.users.decorators import admin_required, teacher_required, student_required
from app.users.functions import create_user, add_roles_to_user, is_admin, is_student, is_teacher
from app.users.models import Role, User, UserRoles

school_blueprint = Blueprint("school_blueprint", __name__)


@school_blueprint.route("/signup", methods=("POST", "GET"))
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        created_successfully = create_school(
            school_name=form.school_name.data,
            admin_forename=form.forename.data,
            admin_surname=form.surname.data,
            admin_password=form.password.data
        )
        if created_successfully:
            return redirect(url_for(".home"))
    return render_template("school/signup.html", form=form)


@school_blueprint.route("/home")
@login_required
def home():
    name = g.user.forename + " " + g.user.surname
    user_roles = UserRoles.select().where(UserRoles.user_id == g.user.user_id)
    roles = [Role.get(Role.role_id == user_role.role_id).role_name for user_role in user_roles]
    return render_template("school/home.html", name=name, roles=roles)


@school_blueprint.route("/user-listing")
@login_required
@admin_required
def user_listing():
    school = School.get(School.school_id == g.user.school_id)
    users = get_users_in_school(school)
    roles = {}
    for user in users:
        roles[user.user_id] = ",".join(get_role_names(user))

    return render_template("school/user_listing.html", users=users, roles=roles)


@school_blueprint.route("/add-user", methods=("POST", "GET"))
@login_required
@admin_required
def add_user():
    form = NewUserForm()
    if form.validate_on_submit():
        username = form.forename.data[0] + form.surname.data
        username = username.lower()
        created_successfully = create_user(
            school=g.user.school_id,
            forename=form.forename.data,
            surname=form.surname.data,
            username=username,
            password=form.password.data
        )
        if not created_successfully[0]:
            flash(created_successfully[1])
        else:
            roles = []

            if form.is_admin.data:
                admin = Role.get(
                    Role.school_id == g.user.school_id,
                    Role.role_name == "admin"
                )
                roles.append(admin)

            if form.is_teacher.data:
                teacher = Role.get(
                    Role.school_id == g.user.school_id,
                    Role.role_name == "teacher"
                )
                roles.append(teacher)

            if form.is_student.data:
                student = Role.get(
                    Role.school_id == g.user.school_id,
                    Role.role_name == "student"
                )
                roles.append(student)
            add_roles_to_user(created_successfully[2], roles)

        if True:
            return redirect(url_for(".user_listing"))

    return render_template("school/add_user.html", form=form)


@school_blueprint.route("/modify-user/<id>", methods=("POST", "GET"))
@login_required
@admin_required
def modify_user(id):
    # Fetch user
    try:
        user = User.get(User.user_id == id)
        role_names = get_role_names(user)
    except:
        flash("Error fetching user. Perhaps it does not exist.")
        return redirect(url_for(".add_user"))

    # Check user belongs to g.user's school
    if not (user.school_id == g.user.school_id):
        flash("You do not have permissions to access that user.")
        return redirect(url_for(".add_user"))

    # Load form with user values
    user_data = {
        "forename": user.forename,
        "surname": user.surname,
        "is_admin": "admin" in role_names,
        "is_teacher": "teacher" in role_names,
        "is_student": "student" in role_names
    }

    if request.method == "GET":
        form = ModifyUserForm(**user_data)
    else:
        form = ModifyUserForm()

    if form.validate_on_submit():
        user.forename = form.forename.data
        user.surname = form.surname.data

        roles = []

        if form.is_admin.data:
            admin = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "admin"
            )
            roles.append(admin)
        elif is_admin(user):
            admin = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "admin"
            )
            UserRoles.get(UserRoles.user_id == user.user_id, UserRoles.role_id == admin.role_id).delete_instance()

        if form.is_teacher.data:
            teacher = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "teacher"
            )
            roles.append(teacher)
        elif is_teacher(user):
            teacher = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "teacher"
            )
            UserRoles.get(UserRoles.user_id == user.user_id, UserRoles.role_id == teacher.role_id).delete_instance()

        if form.is_student.data:
            student = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "student"
            )
            roles.append(student)
        elif is_student(user):
            student = Role.get(
                Role.school_id == g.user.school_id,
                Role.role_name == "student"
            )
            UserRoles.get(UserRoles.user_id == user.user_id, UserRoles.role_id == student.role_id).delete_instance()

        add_roles_to_user(user, roles)
        return redirect(url_for(".user_listing"))

    return render_template("school/modify_user.html", form=form)

app/templates/school/add_user.html
{% extends "layout.html" %}
{% from "macros.html" import render_field %}
{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {% for field in form %}
            {{ render_field(field) }}
        {% endfor %}
        <div class="form-group">
            <button type="submit" id="submit" class="btn btn-success col-xs-12">Add User</button>
        </div>
    </form>
{% endblock %}

app/templates/school/home.html
{% extends "layout.html" %}
{% block content %}
    <h2>Hello, {{ name }}</h2>
    <h3>About You</h3>
    <p>Your roles:</p>
    <ul>
        {% for role in roles %}
            <li>{{ role }}</li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/school/modify_user.html
{% extends "layout.html" %}
{% from "macros.html" import render_field %}
{% block content %}
     <form method="POST" action="">
        {{ form.hidden_tag() }}
        {% for field in form %}
            {{ render_field(field) }}
        {% endfor %}
        <button type="submit" id="submit" class="btn btn-success col-xs-12">Modify</button>
    </form>
{% endblock %}

app/templates/school/signup.html
{% extends "layout.html" %}
{% from "macros.html" import render_field %}
{% block content %}
     <form method="POST" action="">
        {{ form.hidden_tag() }}
        {% for field in form %}
            {{ render_field(field) }}
        {% endfor %}
        <button type="submit" id="submit">Sign Up</button>
    </form>
{% endblock %}

app/templates/school/user_listing.html
{% extends "layout.html" %}
{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Roles</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.forename }} {{ user.surname }}</td>
                    <td>{{ roles[user.user_id] }}</td>
                    <td><a href="{{ url_for("school_blueprint.modify_user", id=user.user_id) }}">Modify</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}