app/users/views.py
from flask import Blueprint, redirect, url_for, render_template, flash
from .forms import LoginForm
from .models import User
from peewee import DoesNotExist
from flask.ext.bcrypt import check_password_hash
from flask.ext.login import login_user, current_user, logout_user

users_blueprint = Blueprint("users_blueprint", __name__)


@users_blueprint.route("/login", methods=("POST", "GET"))
def login():
    form = LoginForm()
    print(current_user)
    if form.validate_on_submit():
        try:
            user = User.get(User.username == form.username.data)
        except DoesNotExist:
            flash("Your email or password does not exist.")
        else:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                flash("You have been logged in.")
                return redirect(url_for("school_blueprint.home"))
            else:
                flash("Your email or password does not exist.")
    return render_template("users/login.html", form=form)


@users_blueprint.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out!")
    return redirect(url_for(".login"))

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <h1>Hello, and welcome to Planner Platform</h1>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Planner Platform</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/bootstrap.min.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/style.css") }}">
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Planner Platform</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if is_student(g.user) %}
              <li>
                  <a href="{{ url_for("timetable_blueprint.timetable") }}">Timetable</a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  {% include "navigation/student_nav.html" %}
                </ul>
              </li>
            {% endif %}
            {% if is_teacher(g.user) %}
              <li>
                <a href="{{ url_for("timetable_blueprint.timetable") }}">Timetable</a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teacher<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  {% include "navigation/teacher_nav.html" %}
                </ul>
              </li>
            {% endif %}
            {% if is_admin(g.user) %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  {% include "navigation/admin_nav.html" %}
                </ul>
              </li>
            {% endif %}
            {% if g.user.is_authenticated() %}
                <li>
                    <a href="{{ url_for("users_blueprint.logout") }}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for("users_blueprint.login") }}">Login</a>
                </li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div id="container" class="container">
      
      {% for message in get_flashed_messages() %}
          <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
            <span class="glyphicon glyphicon-remove close-flash"></span>
          </div>
      {% endfor %}

      {% block content %}{% endblock %}

    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="{{ url_for("static", filename="js/bootstrap.min.js") }}"></script>
    <script type="text/javascript" src="{{ url_for("static", filename="js/main.js") }}"></script>
</body>
</html>

app/templates/macros.html
{% macro render_field(field) %}
     {% if field.errors %}
        {%  for error in field.errors %}
            <div class="field-error">{{ error }}</div>
        {% endfor %}
    {% endif %}
    {% if field.type != "CSRFTokenField" %}
        <div class="form-group">
            <label for="{{ field.id }}">{{ field.label.text }}</label>
            {{ field(placeholder=field.label.text, class="form-control") }}
        </div>
    {% endif %}
{% endmacro %}